# Generated by Django 5.0.3 on 2024-03-28 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_adminmessage_sellermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellermessage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.product'),
        ),
    ]
