# Generated by Django 5.0.3 on 2024-03-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=1),
        ),
    ]
