# Generated by Django 5.0.3 on 2024-04-02 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_usercard_purchases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('promo_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('discount_type', models.CharField(choices=[('Percentage', 'p'), ('Flat', 'f')], default='0', max_length=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='PromoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.product')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.promo')),
            ],
        ),
        migrations.AddField(
            model_name='promo',
            name='promo_items',
            field=models.ManyToManyField(through='webapp.PromoItem', to='webapp.product'),
        ),
    ]
