# Generated by Django 5.0.3 on 2024-04-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_promo_promoitem_promo_promo_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='dark',
            field=models.BooleanField(default=False),
        ),
    ]
