# Generated by Django 5.0.3 on 2024-04-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_remove_promo_promo_items_delete_promoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
